# Generated by Django 4.1.7 on 2023-02-19 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('url', models.URLField(default='')),
            ],
            options={
                'verbose_name': 'Категория коллекции',
                'verbose_name_plural': 'Категории коллекций',
            },
        ),
        migrations.CreateModel(
            name='CollectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discount', models.FloatField(default=0)),
                ('url', models.URLField(default='')),
                ('category', models.ManyToManyField(related_name='collections', to='api.collectioncategorymodel')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
            },
        ),
        migrations.CreateModel(
            name='ColorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('color', models.CharField(max_length=7, verbose_name='Цвет')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('url', models.URLField(blank=True, default='', null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='CRMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(max_length=255, verbose_name='Секретный ключ')),
                ('integration_id', models.CharField(max_length=255, verbose_name='Идентификатор интеграции')),
                ('code_auth', models.TextField(verbose_name='Код авторизации')),
                ('access_token', models.TextField(blank=True, max_length=255, null=True, verbose_name='Токен доступа')),
                ('refresh_token', models.TextField(blank=True, max_length=255, null=True, verbose_name='Токен обновления')),
                ('redirect_uri', models.CharField(max_length=255, verbose_name='URI перенаправления')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='CurrencyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField(default=11500)),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('device', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='ManufacturerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('lead_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID сделки')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='ProductCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('url', models.URLField(default='')),
                ('layer', models.IntegerField(default=0)),
                ('last', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.productcategorymodel')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('price', models.FloatField(blank=True, default=0, help_text='Цена в рублях', null=True, verbose_name='Цена')),
                ('discount', models.FloatField(blank=True, default=0, null=True, verbose_name='Скидка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_aktsiya', models.BooleanField(default=False, verbose_name='Акция')),
                ('width', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ширина')),
                ('height', models.CharField(blank=True, max_length=255, null=True, verbose_name='Высота')),
                ('length', models.CharField(blank=True, max_length=255, null=True, verbose_name='Длина')),
                ('material', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Материал')),
                ('availibility', models.BooleanField(default=True, verbose_name='Наличие')),
                ('code', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Артикуль')),
                ('assembly', models.FileField(blank=True, default='', null=True, upload_to='assembly/', verbose_name='Сборка')),
                ('features', models.JSONField(blank=True, null=True, verbose_name='Характеристики')),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='api.productcategorymodel', verbose_name='Категория')),
                ('colors', models.ManyToManyField(blank=True, related_name='product_color', to='api.colormodel', verbose_name='Цвет')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_manufacturer', to='api.manufacturermodel', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Отзыв')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.productmodel', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='ReviewImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.reviewmodel', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Изображение отзыва',
                'verbose_name_plural': 'Изображения отзывов',
            },
        ),
        migrations.CreateModel(
            name='ProductImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('url', models.URLField(blank=True, default='', null=True, verbose_name='Ссылка')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.productmodel')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
            },
        ),
        migrations.CreateModel(
            name='Product3DModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('obj', models.FileField(blank=True, null=True, upload_to='3d/')),
                ('url', models.URLField(default='')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_3d', to='api.productmodel', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': '3D модель',
                'verbose_name_plural': '3D модели',
            },
        ),
        migrations.CreateModel(
            name='OrderItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.ordermodel', verbose_name='Заказ')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.productmodel', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
            },
        ),
        migrations.CreateModel(
            name='FavoriteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='api.customer', verbose_name='Пользователь')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='api.productmodel', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
            },
        ),
        migrations.CreateModel(
            name='CustomerCollectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_collection', to='api.collectionmodel', verbose_name='Товар')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='api.customer', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Коллекция пользователя',
                'verbose_name_plural': 'Коллекции пользователей',
            },
        ),
        migrations.CreateModel(
            name='CustomerCollectionItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_collection_products', to='api.customercollectionmodel', verbose_name='Коллекция')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_collection_products', to='api.productmodel', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Коллекция пользователя',
                'verbose_name_plural': 'Коллекции пользователей',
            },
        ),
        migrations.AddField(
            model_name='collectionmodel',
            name='default_products',
            field=models.ManyToManyField(blank=True, related_name='default_products', to='api.productmodel', verbose_name='Товары по умолчанию'),
        ),
        migrations.AddField(
            model_name='collectionmodel',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_manufacturer', to='api.manufacturermodel', verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='collectionmodel',
            name='products',
            field=models.ManyToManyField(blank=True, to='api.productmodel'),
        ),
        migrations.CreateModel(
            name='CollectionImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('url', models.URLField(blank=True, default='', null=True, verbose_name='Ссылка')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.collectionmodel')),
            ],
            options={
                'verbose_name': 'Изображение коллекции',
                'verbose_name_plural': 'Изображения коллекций',
            },
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='api.customer', verbose_name='Пользователь')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='api.productmodel', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
    ]
