# Generated by Django 4.1.7 on 2023-03-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='sklad_cat',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Категория склада'),
        ),
    ]
