# Generated by Django 4.1.7 on 2023-03-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_productmodel_sklad_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='sklad_cat_2',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Категория склада 2'),
        ),
        migrations.DeleteModel(
            name='CollectionCategoryModel',
        ),
    ]
