# Generated by Django 4.1.7 on 2023-03-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_collectionmodel_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='sklad_collection',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Коллекция склада'),
        ),
    ]
