# Generated by Django 4.1.7 on 2023-03-19 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_productmodel_sklad_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategorymodel',
            name='url',
        ),
    ]
