# Generated by Django 4.1.7 on 2023-03-19 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_productcategorymodel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategorymodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='api.productcategorymodel'),
        ),
    ]
