# Generated by Django 4.1.7 on 2023-03-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_productmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategorymodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
    ]
