# Generated by Django 4.1.7 on 2023-03-23 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_productcategorymodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Категория коллекции',
                'verbose_name_plural': 'Категории коллекций',
            },
        ),
        migrations.AlterField(
            model_name='collectionmodel',
            name='discount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='collectionmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='collectionmodel',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='collection', to='api.productmodel', verbose_name='Товары'),
        ),
        migrations.AddField(
            model_name='collectionmodel',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='collection_category', to='api.collectioncategorymodel', verbose_name='Категория'),
        ),
    ]
