# Generated by Django 4.1.7 on 2023-04-01 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_collectioncategorymodel_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
