# Generated by Django 4.1.7 on 2023-04-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='device',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
