# Generated by Django 4.1.7 on 2023-04-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_customer_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='device',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
