# Generated by Django 4.1.7 on 2023-04-04 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_customer_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewimagemodel',
            name='review',
        ),
        migrations.RemoveField(
            model_name='reviewmodel',
            name='product',
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='api.customercollectionmodel', verbose_name='Коллекция'),
        ),
        migrations.DeleteModel(
            name='FavoriteModel',
        ),
        migrations.DeleteModel(
            name='ReviewImageModel',
        ),
        migrations.DeleteModel(
            name='ReviewModel',
        ),
    ]
