# Generated by Django 4.1.7 on 2023-04-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_reviewimagemodel_review_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crmmodel',
            options={'verbose_name': 'AmoCRM', 'verbose_name_plural': 'AmoCRM'},
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='products',
            field=models.TextField(blank=True, null=True, verbose_name='Товары'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='Сумма заказа'),
        ),
        migrations.DeleteModel(
            name='OrderItemModel',
        ),
    ]
