# Generated by Django 4.1.7 on 2023-04-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_crmmodel_options_ordermodel_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioncategorymodel',
            name='url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='collectionimagesmodel',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='collectionmodel',
            name='url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='colormodel',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='crmmodel',
            name='access_token',
            field=models.TextField(blank=True, null=True, verbose_name='Токен доступа'),
        ),
        migrations.AlterField(
            model_name='crmmodel',
            name='refresh_token',
            field=models.TextField(blank=True, null=True, verbose_name='Токен обновления'),
        ),
        migrations.AlterField(
            model_name='product3dmodel',
            name='url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='productimagesmodel',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка'),
        ),
    ]
