# Generated by Django 4.1.7 on 2023-04-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_collectioncategorymodel_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectioncategorymodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AddField(
            model_name='collectionmodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AddField(
            model_name='collectionmodel',
            name='youtube_video_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='ID Youtube видео'),
        ),
        migrations.AddField(
            model_name='productcategorymodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='youtube_video_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='ID Youtube видео'),
        ),
    ]
