# Generated by Django 4.1.7 on 2023-02-26 11:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainBannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Главный баннер',
                'verbose_name_plural': 'Главные баннеры',
            },
        ),
        migrations.CreateModel(
            name='SecondaryBannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Второстепенный баннер',
                'verbose_name_plural': 'Второстепенные баннеры',
            },
        ),
        migrations.CreateModel(
            name='TopRated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collections', models.ManyToManyField(blank=True, related_name='top_rated', to='api.collectionmodel', verbose_name='Коллекции')),
                ('products', models.ManyToManyField(blank=True, related_name='top_rated', to='api.productmodel', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Топ продаж',
                'verbose_name_plural': 'Топ продаж',
            },
        ),
        migrations.CreateModel(
            name='YouTube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка на видео')),
                ('cover', models.ImageField(upload_to='images/', verbose_name='Обложка')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('channel_link', models.CharField(max_length=255, verbose_name='Ссылка на канал')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'YouTube',
                'verbose_name_plural': 'YouTube',
            },
        ),
        migrations.RenameModel(
            old_name='IntagramTokenModel',
            new_name='InstagramTokenModel',
        ),
        migrations.DeleteModel(
            name='BannerModel',
        ),
        migrations.DeleteModel(
            name='CoverImageModel',
        ),
        migrations.AlterModelOptions(
            name='bestseller',
            options={'verbose_name': 'Лидер продаж', 'verbose_name_plural': 'Лидер продаж'},
        ),
        migrations.RemoveField(
            model_name='bestseller',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bestseller',
            name='image',
        ),
        migrations.RemoveField(
            model_name='bestseller',
            name='name',
        ),
        migrations.AddField(
            model_name='bestseller',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='best_seller', to='api.collectionmodel', verbose_name='Коллекции'),
        ),
        migrations.AddField(
            model_name='bestseller',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='best_seller', to='api.productmodel', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='bestseller',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='bestseller',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='pagesmodel',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент'),
        ),
    ]
