# Generated by Django 4.1.7 on 2023-02-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_mainbannermodel_secondarybannermodel_toprated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainbannermodel',
            name='link',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='secondarybannermodel',
            name='link',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Ссылка'),
        ),
    ]
