# Generated by Django 4.1.7 on 2023-03-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_mainbannermodel_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondarybannermodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='secondarybannermodel',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
