# Generated by Django 4.1.7 on 2023-03-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_secondarybannermodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube',
            name='title',
            field=models.TextField(verbose_name='Заголовок'),
        ),
    ]
