# Generated by Django 4.1.7 on 2023-03-23 11:19

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_youtube_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactsmodel',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, map_attrs={'center': [69.2401, 41.2995], 'marker_color': 'red'}, null=True, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='contactsmodel',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон номер 1'),
        ),
    ]
