# Generated by Django 4.1.7 on 2023-04-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_catalog_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
    ]
